name: Android CI/CD

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # # - name: Set up Node.js
      # #   uses: actions/setup-node@v2
      # #   with:
      # #     node-version: 16  # Adjust to your project's Node.js version

      # - name: Install Dependencies with Yarn
      #   run: yarn install
        
      # - name: Setup Java
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'
      #     distribution: 'adopt'

      # # - name: Build Android APK
      # #   run: react-native run-android  # Replace with your build script
        
      # - name: Setup Android SDK
      #   uses: android-actions/setup-android@v2
      #   with:
      #     sdk-platform: 'platforms;android-30'
          
      # - name: Build and Test
      #   run: |
      #     chmod +x android/gradlew
      #     cd android && ./gradlew assembleRelease
      
          
      # - name: Upload APK Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: android-apk
      #     path: android/app/build/outputs/apk/release/app-release.apk

      - name: Install Nodemailer
        run: npm install nodemailer

     
        
      - name: Send Email
        run: |
          curl -X POST \
          --url 'https://api.sendgrid.com/v3/mail/send' \
          --header "Authorization: Bearer ${{ secrets.SENDGRID_API_KEY }}" \
          -- header 'Content-Type: application/json' \
          --data '{
            "personalizations": [
              {
                "to": [{"email": "naidu4cse@gmail.com"}],
                "subject": "Android APK"
              }
            ],
            "from": {"email": "naidualamuru.com"},
            "content": [
              {
                "type": "text/plain",
                "value": "Here's the Android APK you requested."
              }
            ],
            "attachments": [
              {
                "content": "'$(base64 -w 0 path/to/directory/app/build/outputs/apk/debug/*.apk)'",
                "filename": "your-app.apk"
              }
            ]
          }'


# #Sending apk file to Gmail to download and test it
#       - name: Send Email
#         uses: dawidd6/action-send-mail@v3
#         with:
#           server_address: smtp.gmail.com
#           server_port: 587
#           username: ${{secrets.USER_NAME}}
#           password: ${{secrets.EMAIL_PASSWORD}}  # Store your email password as a GitHub secret
#           from: ${{secrets.USER_NAME}}
#           to: naidu4cse@gmail.com
#           subject: Android APK
#           message: Here's the Android APK you requested.
#           attachments: "android/app/build/outputs/apk/release/app-release.apk"
#   # deploy:
  #   name: Deploy to Google Play
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Set up JDK
  #       uses: actions/setup-java@v2
  #       with:
  #         java-version: 11  # Adjust to your JDK version

  #     - name: Download APK Artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: android-apk
